server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ask_me?useUnicode=true
    username: root
    password: 1234ASdf
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update